version: 2.1

jobs:
  build:
    docker:
      - image: node:16.15.0

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run: yarn install

      # Build project
      - run: yarn build

      # Run tests
      - run: yarn test

      # # Publish to NPM only on merge to master
      # - name: Publish to NPM
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      #     yarn publish --non-interactive
