version: 2

on:
  push:
    branches:
      - master
jobs:
  build:
    docker:
      - image: node:16.15.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      - run: yarn build
      - run: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run:
          name: Run build
          command: export NODE_OPTIONS="--no-warnings" yarn build

      # - name: Publish to NPM
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      #     yarn publish --non-interactive
