version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      - run:
          name: Build project
          command: yarn build:all
      - run:
          name: Run CI
          command: yarn lint:ci
      - run:
          name: Run tests
          command: yarn coverage

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          command: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: yarn publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
